// MVP 목업 데이터 - Supabase 연동 전 UI 검증용
import { Post, Comment, User } from '../types';

export const MOCK_USER: User = {
  id: 'mock-user-1',
  phone_hash: 'hashed_1234',
  nickname: '당뇨_3421',
  role: 'patient',
  disease_ids: ['diabetes', 'hypertension'],
  age_group: '40대',
  diagnosis_year: 2020,
  created_at: '2024-01-01T00:00:00Z',
};

export const MOCK_POSTS: Post[] = [
  {
    id: '1',
    author_id: 'user-2',
    author_nickname: '유방암_8821',
    author_role: 'patient',
    disease_id: 'breast_cancer',
    post_type: 'unsaid_to_doctor',
    title: '항암 중 탈모가 이렇게 힘들 줄 몰랐어요',
    content: '선생님한테 탈모 얘기를 꺼내기가 너무 부끄러웠어요. 그냥 "괜찮아요" 하고 나왔는데... 집에 와서 거울 보다가 혼자 많이 울었어요. 이런 마음 공유할 데가 없었는데 여기서는 말할 수 있을 것 같아서요.',
    reactions: { helpful: 24, same: 45, cheer: 67 },
    comment_count: 12,
    user_reaction: null,
    created_at: '2024-04-28T09:00:00Z',
    updated_at: '2024-04-28T09:00:00Z',
  },
  {
    id: '2',
    author_id: 'user-3',
    author_nickname: '당뇨_환우_5531',
    author_role: 'caregiver',
    disease_id: 'diabetes',
    post_type: 'treatment_experience',
    title: '아버지 인슐린 맞는 거 보조한 지 3년째입니다',
    content: '처음엔 너무 무서워서 손이 떨렸는데 이제는 익숙해졌어요. 그래도 아버지가 아플 때마다 보호자로서 무력감이 있어요. 같은 상황의 보호자분들 계세요?',
    reactions: { helpful: 18, same: 31, cheer: 22 },
    comment_count: 8,
    user_reaction: 'same',
    created_at: '2024-04-27T14:30:00Z',
    updated_at: '2024-04-27T14:30:00Z',
  },
  {
    id: '3',
    author_id: 'user-4',
    author_nickname: '루푸스_9912',
    author_role: 'patient',
    disease_id: 'lupus',
    post_type: 'question',
    title: '하이드록시클로로퀸 복용 중 눈 검사 주기 어떻게 하세요?',
    content: '의사 선생님이 눈 검사를 정기적으로 받으라고 하셨는데 구체적인 주기를 까먹었어요. 6개월마다인가요 1년마다인가요? 같은 약 드시는 분들 어떻게 하시는지 궁금합니다.',
    reactions: { helpful: 9, same: 5, cheer: 2 },
    comment_count: 5,
    user_reaction: null,
    created_at: '2024-04-26T11:00:00Z',
    updated_at: '2024-04-26T11:00:00Z',
  },
  {
    id: '4',
    author_id: 'user-5',
    author_nickname: '크론병_2244',
    author_role: 'patient',
    disease_id: 'crohns',
    post_type: 'hospital_review',
    title: '서울아산병원 소화기내과 - 솔직한 후기',
    content: '대기시간은 길지만 교수님이 정말 꼼꼼하게 봐주세요. 제 증상을 다 말했더니 메모까지 하시면서 들어주셨어요. 처음으로 "제대로 진료받았다"는 느낌이 들었습니다. 단점은 주차비가 너무 비싸요.',
    reactions: { helpful: 41, same: 3, cheer: 7 },
    comment_count: 15,
    user_reaction: 'helpful',
    created_at: '2024-04-25T16:00:00Z',
    updated_at: '2024-04-25T16:00:00Z',
  },
];

export const MOCK_COMMENTS: Comment[] = [
  {
    id: 'c1',
    post_id: '1',
    author_id: 'user-10',
    author_nickname: '유방암_환우_3311',
    author_role: 'caregiver',
    parent_id: null,
    content: '저도 딸이 항암할 때 탈모 때문에 많이 힘들어했어요. 그 고통이 얼마나 컸는지 지금도 생각나요. 혼자 참지 않으셔도 돼요 💙',
    reactions: { helpful: 5, same: 12, cheer: 8 },
    created_at: '2024-04-28T10:00:00Z',
  },
  {
    id: 'c2',
    post_id: '1',
    author_id: 'user-11',
    author_nickname: '유방암_4422',
    author_role: 'patient',
    parent_id: null,
    content: '저도 완전히 같은 경험이에요. 선생님이 바빠 보여서 탈모 얘기를 못 꺼냈는데... 지금 생각하면 말했어야 했는데. 여기서 이렇게 털어놓으니까 좀 나아지는 느낌이에요.',
    reactions: { helpful: 3, same: 18, cheer: 4 },
    created_at: '2024-04-28T10:30:00Z',
  },
];
